# Smart ZYNQ SL V1.3B + ACM9767; inherited V1 DAC pin mapping.
# Check the actual board revision and never directly plug the 36-pin DAC into J5.
set_property PACKAGE_PIN M19 [get_ports clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]
create_clock -name clk_50m -period 20.000 [get_ports clk_50m]
set_property PACKAGE_PIN M17 [get_ports UART_0_0_rxd]
set_property PACKAGE_PIN L17 [get_ports UART_0_0_txd]
set_property PACKAGE_PIN K21 [get_ports key1_n]
set_property IOSTANDARD LVCMOS33 [get_ports {UART_0_0_rxd UART_0_0_txd key1_n}]
set_property PACKAGE_PIN H19 [get_ports {dac_a_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[0]}]
set_property PACKAGE_PIN H20 [get_ports {dac_a_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[1]}]
set_property PACKAGE_PIN E18 [get_ports {dac_a_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[2]}]
set_property PACKAGE_PIN F18 [get_ports {dac_a_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[3]}]
set_property PACKAGE_PIN F17 [get_ports {dac_a_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[4]}]
set_property PACKAGE_PIN G17 [get_ports {dac_a_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[5]}]
set_property PACKAGE_PIN C17 [get_ports {dac_a_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[6]}]
set_property PACKAGE_PIN C18 [get_ports {dac_a_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[7]}]
set_property PACKAGE_PIN G19 [get_ports {dac_a_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[8]}]
set_property PACKAGE_PIN F19 [get_ports {dac_a_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[9]}]
set_property PACKAGE_PIN E20 [get_ports {dac_a_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[10]}]
set_property PACKAGE_PIN E19 [get_ports {dac_a_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[11]}]
set_property PACKAGE_PIN D22 [get_ports {dac_a_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[12]}]
set_property PACKAGE_PIN C22 [get_ports {dac_a_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_data[13]}]
set_property PACKAGE_PIN B22 [get_ports {dac_b_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[0]}]
set_property PACKAGE_PIN B21 [get_ports {dac_b_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[1]}]
set_property PACKAGE_PIN B17 [get_ports {dac_b_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[2]}]
set_property PACKAGE_PIN B16 [get_ports {dac_b_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[3]}]
set_property PACKAGE_PIN A17 [get_ports {dac_b_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[4]}]
set_property PACKAGE_PIN A16 [get_ports {dac_b_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[5]}]
set_property PACKAGE_PIN D20 [get_ports {dac_b_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[6]}]
set_property PACKAGE_PIN C20 [get_ports {dac_b_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[7]}]
set_property PACKAGE_PIN B15 [get_ports {dac_b_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[8]}]
set_property PACKAGE_PIN C15 [get_ports {dac_b_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[9]}]
set_property PACKAGE_PIN D17 [get_ports {dac_b_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[10]}]
set_property PACKAGE_PIN D16 [get_ports {dac_b_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[11]}]
set_property PACKAGE_PIN D15 [get_ports {dac_b_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[12]}]
set_property PACKAGE_PIN E15 [get_ports {dac_b_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_data[13]}]
set_property PACKAGE_PIN D18 [get_ports {dac_a_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_clk}]
set_property PACKAGE_PIN C19 [get_ports {dac_a_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_a_wrt}]
set_property PACKAGE_PIN E16 [get_ports {dac_b_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_clk}]
set_property PACKAGE_PIN F16 [get_ports {dac_b_wrt}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_b_wrt}]
set_property SLEW FAST [get_ports {dac_a_data[*]}]
set_property DRIVE 8 [get_ports {dac_a_data[*]}]
set_property SLEW FAST [get_ports {dac_b_data[*]}]
set_property DRIVE 8 [get_ports {dac_b_data[*]}]
set_property SLEW FAST [get_ports {dac_a_clk}]
set_property DRIVE 8 [get_ports {dac_a_clk}]
set_property SLEW FAST [get_ports {dac_a_wrt}]
set_property DRIVE 8 [get_ports {dac_a_wrt}]
set_property SLEW FAST [get_ports {dac_b_clk}]
set_property DRIVE 8 [get_ports {dac_b_clk}]
set_property SLEW FAST [get_ports {dac_b_wrt}]
set_property DRIVE 8 [get_ports {dac_b_wrt}]
# Forwarded clocks and DAC setup/hold, assuming matched short data/clock paths.
create_clock -name dac_wrt_virtual50 -period 20.000 -waveform {10.000 20.000}
set_output_delay -clock dac_wrt_virtual50 -max 2.0 [get_ports {dac_a_data[*] dac_b_data[*]}]
set_output_delay -clock dac_wrt_virtual50 -min -1.5 [get_ports {dac_a_data[*] dac_b_data[*]}]
# At 50 MSPS WRT-to-CLK is nominally 5 ns. Bench-check real Dupont-wire skew.
set_property PACKAGE_PIN G15 [get_ports trigger_in]
set_property PACKAGE_PIN G16 [get_ports marker_out]
set_property IOSTANDARD LVCMOS33 [get_ports {trigger_in marker_out}]
set_property PULLDOWN true [get_ports trigger_in]
# Both pins are asynchronous to the sample clock. key1_n only asserts reset;
# trigger_in is sampled by the two-stage ASYNC_REG synchronizer.
set_false_path -from [get_ports {key1_n trigger_in}]

# RTL8211E, Bank 35. Board schematic page 11; TX and RX are PHY-relative.
set_property PACKAGE_PIN G21 [get_ports MDIO_PHY_0_mdc]
set_property PACKAGE_PIN H22 [get_ports MDIO_PHY_0_mdio_io]
set_property PACKAGE_PIN A22 [get_ports {RGMII_0_rd[0]}]
set_property PACKAGE_PIN A18 [get_ports {RGMII_0_rd[1]}]
set_property PACKAGE_PIN A19 [get_ports {RGMII_0_rd[2]}]
set_property PACKAGE_PIN B20 [get_ports {RGMII_0_rd[3]}]
set_property PACKAGE_PIN A21 [get_ports RGMII_0_rx_ctl]
set_property PACKAGE_PIN B19 [get_ports RGMII_0_rxc]
set_property PACKAGE_PIN E21 [get_ports {RGMII_0_td[0]}]
set_property PACKAGE_PIN F21 [get_ports {RGMII_0_td[1]}]
set_property PACKAGE_PIN F22 [get_ports {RGMII_0_td[2]}]
set_property PACKAGE_PIN G20 [get_ports {RGMII_0_td[3]}]
set_property PACKAGE_PIN G22 [get_ports RGMII_0_tx_ctl]
set_property PACKAGE_PIN D21 [get_ports RGMII_0_txc]
set_property IOSTANDARD LVCMOS33 [get_ports {MDIO_PHY_0_mdc MDIO_PHY_0_mdio_io RGMII_0_rd[*] RGMII_0_rx_ctl RGMII_0_rxc RGMII_0_td[*] RGMII_0_tx_ctl RGMII_0_txc}]
# The GMII-to-RGMII core cascades two clock buffers for 10/100 operation.
# Their shared 25/2.5 MHz mux cannot occupy the two adjacent sites already
# used by the PS FCLK buffers. The resulting dedicated-route exception is
# limited to this low-speed intermediate net; inspect routed clock timing.
set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets awg_system_i/eth_bridge/U0/gmii_clk_25m_or_2_5m]
create_clock -name rgmii_rxclk -period 8.000 [get_ports RGMII_0_rxc]
# PHY receive interface: model both DDR edges; refine with measured board delay.
set_input_delay -clock rgmii_rxclk -max 2.5 [get_ports {RGMII_0_rd[*] RGMII_0_rx_ctl}]
set_input_delay -clock rgmii_rxclk -min 0.5 [get_ports {RGMII_0_rd[*] RGMII_0_rx_ctl}]
set_input_delay -clock rgmii_rxclk -clock_fall -add_delay -max 2.5 [get_ports {RGMII_0_rd[*] RGMII_0_rx_ctl}]
set_input_delay -clock rgmii_rxclk -clock_fall -add_delay -min 0.5 [get_ports {RGMII_0_rd[*] RGMII_0_rx_ctl}]
